/*
 Copyright (c) 2013, Pixel & Tonic, Inc.
 @license   http://buildwithcraft.com/license Craft License Agreement
 @link      http://buildwithcraft.com
*/
(function(c){Craft.MatrixInput=Garnish.Base.extend({id:null,blockTypes:null,blockTypesByHandle:null,inputNamePrefix:null,inputIdPrefix:null,$container:null,$blockContainer:null,$newBlockBtnContainer:null,$newBlockBtnGroup:null,$newBlockBtnGroupBtns:null,blockSort:null,totalNewBlocks:0,init:function(a,b,d){this.id=a;this.blockTypes=b;this.inputNamePrefix=d;this.inputIdPrefix=Craft.formatInputId(this.inputNamePrefix);this.$container=c("#"+this.id);this.$blockContainer=this.$container.children(".blocks");
this.$newBlockBtnContainer=this.$container.children(".buttons");this.$newBlockBtnGroup=this.$newBlockBtnContainer.children(".btngroup");this.$newBlockBtnGroupBtns=this.$newBlockBtnGroup.children(".btn");this.$newBlockMenuBtn=this.$newBlockBtnContainer.children(".menubtn");this.setNewBlockBtn();this.blockTypesByHandle={};for(b=0;b<this.blockTypes.length;b++)a=this.blockTypes[b],this.blockTypesByHandle[a.handle]=a;d=this.$blockContainer.children();var g=Craft.MatrixInput.getCollapsedBlockIds();this.blockSort=
new Garnish.DragSort(d,{caboose:"<div/>",handle:"> .actions > .move",axis:"y",helperOpacity:0.9});for(b=0;b<d.length;b++){var h=c(d[b]);a=h.data("id");(a="string"==typeof a&&a.match(/new(\d+)/))&&a[1]>this.totalNewBlocks&&(this.totalNewBlocks=parseInt(a[1]));a=new n(this,h);a.id&&-1!=c.inArray(""+a.id,g)&&a.collapse()}this.addListener(this.$newBlockBtnGroupBtns,"click",function(a){a=c(a.target).data("type");this.addBlock(a)});new Garnish.MenuBtn(this.$newBlockMenuBtn,{onOptionSelect:c.proxy(function(a){a=
c(a).data("type");this.addBlock(a)},this)});this.addListener(Garnish.$win,"resize","setNewBlockBtn")},setNewBlockBtn:function(){this.$newBlockBtnGroup.removeClass("hidden").width()>this.$container.width()?(this.$newBlockBtnGroup.addClass("hidden"),this.$newBlockMenuBtn.removeClass("hidden")):(this.$newBlockBtnGroup.removeClass("hidden"),this.$newBlockMenuBtn.addClass("hidden"))},addBlock:function(a,b){this.totalNewBlocks++;for(var d="new"+this.totalNewBlocks,g='<div class="matrixblock" data-id="'+
d+'"><input type="hidden" name="'+this.inputNamePrefix+"["+d+'][type]" value="'+a+'"/><input type="hidden" name="'+this.inputNamePrefix+"["+d+'][enabled]" value="1"/><div class="actions"><div class="status off" title="'+Craft.t("Disabled")+'"></div><a class="settings icon menubtn" title="'+Craft.t("Actions")+'" role="button"></a> <div class="menu padded" data-align="right"><ul><li><a data-icon="collapse" data-action="collapse">'+Craft.t("Collapse")+'</a></li><li class="hidden"><a data-icon="expand" data-action="expand">'+
Craft.t("Expand")+'</a></li><li><a data-icon="disabled" data-action="disable">'+Craft.t("Disable")+'</a></li><li class="hidden"><a data-icon="enabled" data-action="enable">'+Craft.t("Enable")+"</a></li></ul><hr/><ul>",h=0;h<this.blockTypes.length;h++)var l=this.blockTypes[h],g=g+('<li><a data-icon="+" data-action="add" data-type="'+l.handle+'">'+Craft.t("Add {type} above",{type:l.name})+"</a></li>");var g=g+('</ul><hr/><ul><li><a data-icon="remove" data-action="delete">'+Craft.t("Delete")+'</a></li></ul></div><a class="move icon" title="'+
Craft.t("Reorder")+'" role="button"></a> </div></div>'),e=c(g);b?e.insertBefore(b):e.appendTo(this.$blockContainer);var k=c('<div class="fields"/>').appendTo(e),g=this.getParsedBlockHtml(this.blockTypesByHandle[a].bodyHtml,d),f=this.getParsedBlockHtml(this.blockTypesByHandle[a].footHtml,d);c(g).appendTo(k);d=e.is(":last-child")?20:0;e.css(this.getHiddenBlockCss(e)).animate({opacity:1,marginBottom:d},"fast",c.proxy(function(){e.css("margin-bottom","");c("body").append(f);Craft.initUiElements(k);new n(this,
e);this.blockSort.addItems(e)},this))},getHiddenBlockCss:function(a){var b=-a.outerHeight();a.is(":only-child")?b-=16:a.is(":last-child")&&(b+=16);return{opacity:0,marginBottom:b}},getParsedBlockHtml:function(a,b){return"string"==typeof a?a.replace(/__BLOCK__/g,b):""}},{collapsedBlockStorageKey:"Craft-"+Craft.siteUid+".MatrixInput.collapsedBlocks",getCollapsedBlockIds:function(){return"string"==typeof localStorage[Craft.MatrixInput.collapsedBlockStorageKey]?Craft.filterArray(localStorage[Craft.MatrixInput.collapsedBlockStorageKey].split(",")):
[]},setCollapsedBlockIds:function(a){localStorage[Craft.MatrixInput.collapsedBlockStorageKey]=a.join(",")}});var n=Garnish.Base.extend({matrix:null,$container:null,$fieldsContainer:null,$previewContainer:null,$actionMenu:null,id:null,collapsed:!1,init:function(a,b){this.matrix=a;this.$container=b;this.$fieldsContainer=b.children(".fields");parseInt(this.$container.data("id"))==this.$container.data("id")&&(this.id=this.$container.data("id"));var d=this.$container.find("> .actions > .settings"),d=new Garnish.MenuBtn(d);
this.$actionMenu=d.menu.$container;d.menu.settings.onOptionSelect=c.proxy(this,"onMenuOptionSelect");this.addListener(this.$container,"dblclick",function(a){a.pageY<=this.$container.offset().top+30&&(a.preventDefault(),this.toggle())})},toggle:function(){this.collapsed?this.expand():this.collapse(!0)},collapse:function(a){if(!this.collapsed){this.$previewContainer||(this.$previewContainer=c('<div class="preview" style="display: none;"/>').appendTo(this.$container));for(var b="",d=this.$fieldsContainer.children(),
g=0;g<d.length;g++){for(var h=c(d[g]),l=h.children(".input").find('select,input[type!="hidden"],textarea,.label'),e="",k=0;k<l.length;k++){var f=c(l[k]);if(f.hasClass("label")){var m=f.parent().parent();if(m.hasClass("lightswitch")&&(m.hasClass("on")&&f.hasClass("off")||!m.hasClass("on")&&f.hasClass("on")))continue;f=f.text()}else f=Craft.getText(Garnish.getInputPostVal(f));f instanceof Array&&(f=f.join(", "));f&&(f=Craft.trim(f))&&(e&&(e+=", "),e+=f)}e&&(b&&(b+=" <span>|</span> "),b+="<strong>"+
Craft.trim(h.children(".heading").text())+":</strong> "+e)}this.$previewContainer.html(b);this.$previewContainer.stop();this.$fieldsContainer.stop();this.$container.stop();a?(this.$previewContainer.fadeIn("fast"),this.$fieldsContainer.fadeOut("fast"),this.$container.animate({height:0},"fast")):(this.$previewContainer.show(),this.$fieldsContainer.hide(),this.$container.css({height:0}));setTimeout(c.proxy(function(){this.$actionMenu.find("a[data-action=collapse]:first").parent().addClass("hidden");
this.$actionMenu.find("a[data-action=expand]:first").parent().removeClass("hidden")},this),200);this.id&&"undefined"!==typeof Storage&&(a=Craft.MatrixInput.getCollapsedBlockIds(),-1==c.inArray(""+this.id,a)&&(a.push(this.id),Craft.MatrixInput.setCollapsedBlockIds(a)));this.collapsed=!0}},expand:function(){if(this.collapsed){this.$previewContainer.stop();this.$fieldsContainer.stop();this.$container.stop();var a=this.$container.height();this.$container.height("auto");this.$fieldsContainer.show();var b=
this.$container.height();this.$container.height(a);this.$fieldsContainer.hide().fadeIn("fast");this.$previewContainer.fadeOut("fast");this.$container.animate({height:b},"fast",c.proxy(function(){this.$container.height("auto")},this));setTimeout(c.proxy(function(){this.$actionMenu.find("a[data-action=collapse]:first").parent().removeClass("hidden");this.$actionMenu.find("a[data-action=expand]:first").parent().addClass("hidden")},this),200);this.id&&"undefined"!==typeof Storage&&(a=Craft.MatrixInput.getCollapsedBlockIds(),
b=c.inArray(""+this.id,a),-1!=b&&(a.splice(b,1),Craft.MatrixInput.setCollapsedBlockIds(a)));this.collapsed=!1}},disable:function(){this.$container.children('input[name$="[enabled]"]:first').val("");this.$container.addClass("disabled");setTimeout(c.proxy(function(){this.$actionMenu.find("a[data-action=disable]:first").parent().addClass("hidden");this.$actionMenu.find("a[data-action=enable]:first").parent().removeClass("hidden")},this),200);this.collapse(!0)},enable:function(){this.$container.children('input[name$="[enabled]"]:first').val("1");
this.$container.removeClass("disabled");setTimeout(c.proxy(function(){this.$actionMenu.find("a[data-action=disable]:first").parent().removeClass("hidden");this.$actionMenu.find("a[data-action=enable]:first").parent().addClass("hidden")},this),200);this.expand()},onMenuOptionSelect:function(a){a=c(a);switch(a.data("action")){case "collapse":this.collapse(!0);break;case "expand":this.expand();break;case "disable":this.disable();break;case "enable":this.enable();break;case "add":a=a.data("type");this.matrix.addBlock(a,
this.$container);break;case "delete":this.selfDestruct()}},selfDestruct:function(){this.$container.animate(this.matrix.getHiddenBlockCss(this.$container),"fast",c.proxy(function(){this.$container.remove()},this))}})})(jQuery);

//# sourceMappingURL=MatrixInput.min.map
