/*
 Copyright (c) 2013, Pixel & Tonic, Inc.
 @license   http://buildwithcraft.com/license Craft License Agreement
 @link      http://buildwithcraft.com
*/
(function(f){Craft.RichTextInput=Garnish.Base.extend({id:null,init:function(g,k,l,c){this.id=g;c.lang=k;"undefined"==typeof c.buttonsCustom&&(c.buttonsCustom={});c.buttonsCustom.image={title:Craft.t("Insert image"),dropdown:{from_web:{title:Craft.t("Insert URL"),callback:function(){this.imageShow()}},from_assets:{title:Craft.t("Choose image"),callback:function(){this.selectionSave();var b=this;"undefined"==typeof this.assetSelectionModal?this.assetSelectionModal=Craft.createElementSelectorModal("Asset",
{storageKey:"RichTextFieldType.ChooseImage",multiSelect:!0,criteria:{kind:"image"},onSelect:f.proxy(function(a,c){if(a.length){b.selectionRestore();for(var d=0;d<a.length;d++){var e=a[d],e=e.url+"#asset:"+e.id;c&&(e+=":"+c);b.insertNode(f('<img src="'+e+'" />')[0]);b.sync()}this.observeImages();b.dropdownHideAll()}},this),closeOtherModals:!1,canSelectImageTransforms:!0}):(this.assetSelectionModal.shiftModalToEnd(),this.assetSelectionModal.show())}}}};c.buttonsCustom.link={title:Craft.t("Link"),dropdown:{link_entry:{title:Craft.t("Link to an entry"),
callback:function(){this.selectionSave();var b=this;"undefined"==typeof this.entrySelectionModal?this.entrySelectionModal=Craft.createElementSelectorModal("Entry",{storageKey:"RichTextFieldType.LinkToEntry",sources:l,onSelect:function(a){if(a.length){b.selectionRestore();a=a[0];var c=a.url+"#entry:"+a.id,d=b.getSelectionText();b.insertNode(f('<a href="'+c+'">'+(0<d.length?d:a.label)+"</a>")[0]);b.sync()}b.dropdownHideAll()},closeOtherModals:!1}):(this.entrySelectionModal.shiftModalToEnd(),this.entrySelectionModal.show())}},
link_asset:{title:Craft.t("Link to an asset"),callback:function(){this.selectionSave();var b=this;"undefined"==typeof this.assetLinkSelectionModal?this.assetLinkSelectionModal=Craft.createElementSelectorModal("Asset",{storageKey:"RichTextFieldType.LinkToAsset",onSelect:function(a){if(a.length){b.selectionRestore();a=a[0];var c=a.url+"#asset:"+a.id,d=b.getSelectionText();b.insertNode(f('<a href="'+c+'">'+(0<d.length?d:a.label)+"</a>")[0]);b.sync()}b.dropdownHideAll()},closeOtherModals:!1,canSelectImageTransforms:!0}):
(this.assetLinkSelectionModal.shiftModalToEnd(),this.assetLinkSelectionModal.show())}},link:{title:Craft.t("Insert link"),func:"linkShow"},unlink:{title:Craft.t("Unlink"),exec:"unlink"}}};g=f("#"+this.id);g.redactor(c);var h=g.data("redactor");if("undefined"!=typeof h.fullscreen&&"function"==typeof h.toggleFullscreen)Craft.cp.on("beforeSaveShortcut",function(){h.fullscreen&&h.toggleFullscreen()})}})})(jQuery);

//# sourceMappingURL=RichTextInput.min.map
